### ISSUE TITLE
Heading - Font Weight

### ISSUE THREAD

**Issue by kristaleemcphee** [reaktivstudios/gppro-entry-content#2]
The default for the heading tags is 700 (bold) in the extension.  I think it should be considered adding "always_write" to the font weight for the headings.  Quite a few themes by default use a lighter weight, and the majority of users want to make the heading bold.  They are unable to for the themes that by default do not use the 700 weight.

**Comment by kristaleemcphee** [comment]
@norcross this was posted a while ago - and it has come up a few times since.

**Comment by norcross** [comment]
so is this for all the heading tags?
